<!-- application/views/scripts/contact/index.phtml -->

<p><a href="<?php
    echo $this->url(
            array(
        'controller' => 'contact',
        'action' => 'sign'
            ), 'default', true)
    ?>">Contact Us</a></p>

Contact Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
        <dt><?php echo $this->escape($entry->email) ?></dt>
        <dd><?php echo $this->escape($entry->comment) ?></dd>
    <?php endforeach ?>
</dl>