<!-- application/layouts/scripts/layout.phtml -->
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework ICT');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta name="description" content="">
                <meta name="author" content="">
                    <?php echo $this->headMeta(); ?>
                    <?php echo $this->headTitle(); ?>
                    <?php
                    $this->headLink()->appendStylesheet($this->baseUrl("css/main.css"))
                            ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
                    echo $this->headLink();
                    $this->headScript()->appendFile($this->baseUrl("js/jquery.min.js"))
                            ->appendFile($this->baseUrl("js/bootstrap.bundle.min.js"))
                            ->appendFile($this->baseUrl("js/jquery.magnific-popup.min.js"))
                            ->appendFile($this->baseUrl("js/jquery.easing.min.js"))
                            ->appendFile($this->baseUrl("js/freelancer.min.js"));
                    echo $this->headScript();
                    ?>

                    </head>
                    <body id="page-top">



                        <?php echo $this->layout()->content ?>

                        <!-- Navigation -->
                        <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
                            <div class="container">
                                <a class="navbar-brand js-scroll-trigger" href="<?php $this->baseUrl() ?>">Zend Framework 1.12 Project</a>
                                <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                                    Menu
                                    <i class="fa fa-bars"></i>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarResponsive">
                                    <ul class="navbar-nav ml-auto">
                                        
                                        <li style="color: white;margin-top: 16px;margin-right: -40px; ">
                                                   
                                            <a href="<?php echo $this->loggedInAs() ?>"><?php echo $this->loggedInAsName(); ?></a>
                                                                                  
                                        </li>
                                        
                                        
                                        <?php echo $this->navigation()->menu()->setUlClass('navigacija'); ?>
                                        
                                    </ul>
                                </div>
                            </div>
                        </nav>



                        <!-- Footer -->
                        

                        <div class="copyright py-4 text-center text-white">
                            <div class="container">
                                <small>Copyright &copy; Zend Framework 1.12 Project</small>
                            </div>
                        </div>

                        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
                        <div class="scroll-to-top d-lg-none position-fixed ">
                            <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>

                    </body>
                    </html>